story = [
        "Il était une fois, le Royaume mystérieux d'Elementaria. Le monde était harmonieusement équilibré grâce aux quatre éléments primordiaux : Feu, Eau, Terre et Air. Chaque élément, unique dans son essence, jouait un rôle crucial pour maintenir l'équilibre de la nature. Cependant, un événement calamiteux s'est produit et a affecté l'ensemble du Royaume.",
        "Les cieux autrefois vifs sont devenus opaques et les vents qui caressaient les terres ont cessé de circuler. Les habitants d'Elementaria ne pouvaient plus respirer facilement, leur âme se fatiguait tandis qu'ils aspiraient à ces jours meilleurs où le monde était rempli de vie.",
        "Les réserves d'eau douce diminuent, la biodiversité se réduit car la dispersion des graines par le vent est moins efficace, maintenir un feu allumé, que ce soit pour se chauffer ou s'éclairer grace aux torches demande du plus en plus d'investissement et, pour courroner le tout, le climat se refroidit.",
        "À la recherche d'une solution à cette énigme, le Conseil des Éléments se réuni dans le grand Temple de l'Harmonie. Après avoir cherché dans les prophéties anciennes, l'Oracle de la Terre est tombé sur une légende pertinente : 'Lorsque l'Air deviendra faible, l'Eau, la terre et le Feu se rallieront pour le rétablir.'",
        "Renouvelé par cette espérance, le Conseil envoya des émissaires dans tout Elementaria pour chercher de braves âmes prêtes à entreprendre une quête pour rassembler les essences l'Eau, de la Terre et du Feu. Ces héros devraient aller à la recherche de ces éléments sous leur forme la plus pure et les rapporter dans le grand Temple de l'Harmonie pour les combiner en un Elixir de Renaissance de l'Air.",
        "VOUS devrez voyager à travers les paysages périlleux mais pittoresques d'Elementaria - depuis les profondes abysses d'Aquatopia, le sanctuaire de l'Eau aux rudes terres de Terra Firma où repose la puissance de la Terre et enfin les plaines volcaniques en éruption de Pyroville où règne le Feu.",
        "Dans chacun de ces domaines, vous devrez démêler les mystères cachés par des gardiens enigmatiques et recueillir les essences les plus pures. Mais prenez garde ! L'Air malade a affaibli les frontières entre les éléments, causant de la confusion et du chaos dans le monde. Vous devrez user de votre habilité pour traverser cette turbulence et ainsi rétablir l'harmonie dans le monde d'Elementaria.",
        "Seulement en rassemblant toutes les trois essences, pourrez vous créer l'Elixir de Renaissance, restaurant la vitalité anémique de l'élément Air et chassant la maladie qui le touche. Et avec un Air rétabli, l'harmonie reprendra à nouveau dans le monde d'Elementaria !"
        ]